name = "NKFtool"
uuid = "6cd5b726-56d4-11ea-3af6-6d4c3007f70c"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.2.2"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
